### ISSUE TITLE
Connect AI Agent locally

### ISSUE THREAD

**Issue by rajapulau** [livekit-examples/voice-assistant-frontend#13]
Hi,

How to connect voice-assistant-frontend locally with ai-agent. I won't run with sandbox. I added my env API key, secret key, and URL but still connected the AI Agent. 

**It's quiet... too quiet. Is your agent lost? Ensure your agent is properly configured and running on your machine.**

![Selection_125](https://github.com/user-attachments/assets/cdd1824c-f770-4b3e-930b-02c79f87519f)

Is there I'm missing?

**Comment by rajapulau** [comment]
oh sorry, 

I forgot comment this code `request_fnc=request,` from template ai agent

**Comment by rahulvk007** [comment]
Hey I am facing the same issue. Could you please elaborate on the fix ?

**Comment by god-ts** [comment]
May I ask where to add the request_fnc=request code?

**Comment by RGDEV2022** [comment]
This is still an issue. How do you fix this? Thanks
