### ISSUE TITLE
Type error: Cannot find module '@livekit/components-react/krisp' or its corresponding type declarations.

### ISSUE THREAD

**Issue by someshfengde** [livekit-examples/voice-assistant-frontend#16]
Type error: Cannot find module '@livekit/components-react/krisp' or its corresponding type declarations.
  There are types at '/vercel/path0/node_modules/@livekit/components-react/dist/krisp.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
  15 | import { NoAgentNotification } from "@/components/icons/NoAgentNotification";
  16 | import { CloseIcon } from "@/components/icons/CloseIcon";
> 17 | import { useKrispNoiseFilter } from '@livekit/components-react/krisp';
     |                                     ^
  18 |
  19 | export default function Page() {
  20 |   const [userDetails, setUserDetails] = useState(null);
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1

**Comment by lukasIO** [comment]
make sure that you set your `moduleResolution: bundler` in the tscconfig.json
