### ISSUE TITLE
Running over HTTPS, and port selection?

### ISSUE THREAD

**Issue by billyg88** [livekit-examples/voice-assistant-frontend#17]
Hello there. 

Im a newbie when it comes to JS/node/express...
I can't for the life of me figure out how to run the front end app over ```HTTPS```

The ```pnpm dev``` command runs the app over ```htttp```.  
Subsequently when I try to access it microphone functionality is unavailable due to browser security. 
I have my SSL certificates..but I have no idea how to use them with this app.  

Also is there a way to specify the ```port``` to run the app on? In some kind of configuration file?

**Comment by davidzhao** [comment]
you will need to set up a secure webserver. The example is a simple next-js example, I recommend checking out their docs: https://nextjs.org/docs

**Comment by billyg88** [comment]
Thanks that really helped ! 

```https://nextjs.org/docs/app/api-reference/cli/next#using-https-during-development```

I literally couldn't get the demo to work without this? Shouldn't this be a prerequisite?
